spring.application.name=rafael_vieira_spring_at

# URL de conexão JDBC
spring.datasource.url=jdbc:postgresql://ep-nameless-mud-ac2zgza8-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

# Credenciais do banco de dados
spring.datasource.username=neondb_owner
spring.datasource.password=npg_YeuDty1MwvJ0
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Estratégia de criação de tabelas (atualiza automaticamente ao rodar a aplicação)
spring.jpa.hibernate.ddl-auto=update